# Generated by Django 3.2.4 on 2021-07-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=3500)),
                ('whoLiked', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1500)),
                ('msgFrom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fromPerson', to=settings.AUTH_USER_MODEL)),
                ('msgTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toPerson', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
