# Generated by Django 3.2.4 on 2021-07-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0002_auto_20210710_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='filesForWeb',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
