# Generated by Django 3.2.4 on 2021-07-11 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BB', '0003_post_filesforweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='whoLiked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
