# Generated by Django 3.2.4 on 2021-07-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filesForWeb',
            field=models.ImageField(blank=True, default='', upload_to='media/images/'),
        ),
    ]
