# Generated by Django 3.2.4 on 2021-07-17 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BB', '0006_alter_post_filesforweb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='whoLiked',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
