# Generated by Django 3.2.4 on 2021-07-17 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BB', '0007_alter_post_wholiked'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='whoDisliked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whoDisliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='whoLiked',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whoLiked', to=settings.AUTH_USER_MODEL),
        ),
    ]
