# Generated by Django 3.2.4 on 2021-07-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BB', '0008_auto_20210717_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='filesForWeb',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
